name: CI/CD - Test & Deploy to Ghaymah

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Prisma generate
        run: npx prisma generate

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to Ghaymah
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ghaymah CLI
        run: curl -sSl https://cli.ghaymah.systems/install.sh | bash

      - name: Login to Ghaymah
        run: $HOME/ghaymah/bin/gy auth login --email "${{ secrets.GHAYMAH_EMAIL }}" --password "${{ secrets.GHAYMAH_PW }}"

      - name: Deploy
        run: $HOME/ghaymah/bin/gy resource app launch
